# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61d252a28317a516ac708d641408a2bbb9146cb760edc4d7b6cd7897b7abf760c8ba045217c2aeee88c7b25e43d12c3424ffa855450a2903a53376c30f23287d

test:
  secret_key_base: 4423ff522ed0375ddac7ed8466cfc7222ea9ec8a8abfd9b5830116a41a15fcec523d1cc6cfb51e449b128b2cd1a6881e755b24a8858487b73c048b22d86fb456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
